function PictureVizII = importfile3(filename, dataLines)
%IMPORTFILE3 Import data from a text file
%  PICTUREVIZII = IMPORTFILE3(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  PICTUREVIZII = IMPORTFILE3(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  PictureVizII = importfile3("C:\Program Files (x86)\Windows Media Player\Visualizations\Picture It! Viz 2\PictureViz_II.dll", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Apr-2019 15:19:33

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["MZLThisprogramcannotberuninDOSmode", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PictureVizII = readtable(filename, opts);

end