function qats = importfile7(filename, dataLines)
%IMPORTFILE7 Import data from a text file
%  QATS = IMPORTFILE7(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  QATS = IMPORTFILE7(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  qats = importfile7("C:\Users\Bondz\Documents\qats.pro.jade", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Apr-2019 13:18:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "#";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["string", "string"];
opts = setvaropts(opts, [1, 2], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
qats = readtable(filename, opts);

end